---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
#Load csv file and filter out 'Both sexes'
suicide_data <- read_csv(file = '~/Library/Mobile Documents/com~apple~CloudDocs/ISDS_3070/Suicide_vs_World_Happiness/data/final_project_data/data.csv') %>% 
  filter(Sex != 'Both sexes') %>% 
  gather(Year, SuicidePer100000, 3:6)

#Load csv files and load only country and happiness rank
world16_happiness_data <- read_csv(file = '~/Library/Mobile Documents/com~apple~CloudDocs/ISDS_3070/Suicide_vs_World_Happiness/data/final_project_data/world-happiness-report/2016.csv') %>% 
  select(Country, HappinessRank, Region)

world15_happiness_data <- read_csv(file = '~/Library/Mobile Documents/com~apple~CloudDocs/ISDS_3070/Suicide_vs_World_Happiness/data/final_project_data/world-happiness-report/2015.csv') %>%  
  select(Country, HappinessRank, Region)

#adds year columns to world_happiness

world15_happiness_data$Year <- 2015

world16_happiness_data$Year <- 2016

#combines both world_happiness data sets to each other
world_happiness <- bind_rows(world15_happiness_data, world16_happiness_data)

#filters out countries that are not within both sets 
suicide_data_combined <- suicide_data %>% 
  filter(Country %in% world_happiness$Country)

#creates final data set to have 5 columns: country, year, sex, suicidesper100000, happiness rank
combined_data_set <- mutate(suicide_data_combined, Year = as.double(Year)) %>% 
  inner_join(world_happiness) %>% 
  filter(Year >= 2015)

# Calculations

# 2016 Calculations
combined_data_set %>% 
  filter(Sex == 'Male' & Year == '2016') %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Sex == 'Female' & Year == '2016') %>% 
  summarise(mean(SuicidePer100000))

# 2015 Calculations

combined_data_set %>% 
  filter(Sex == 'Male' & Year == '2015') %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Sex == 'Female' & Year == '2015') %>% 
  summarise(mean(SuicidePer100000))

#2016 mean sucicdes per region and sex
combined_data_set %>% 
  filter(Region == "Central and Eastern Europe" & Sex == "Female" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Central and Eastern Europe" & Sex == "Male" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Latin America and Caribbean" & Sex == "Female" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Latin America and Caribbean" & Sex == "Male" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Middle East and Northern Africa" & Sex == "Female" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Middle East and Northern Africa" & Sex == "Male" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Southeastern Asia" & Sex == "Female" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Southeastern Asia" & Sex == "Male" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Southern Asia" & Sex == "Female" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Southern Asia" & Sex == "Male" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Sub-Saharan Africa" & Sex == "Female" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Sub-Saharan Africa" & Sex == "Male" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Western Europe" & Sex == "Female" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Western Europe" & Sex == "Male" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))
  
combined_data_set %>% 
  filter(Region == "Australia and New Zealand" & Sex == "Female" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))

combined_data_set %>% 
  filter(Region == "Australia and New Zealand" & Sex == "Male" & Year == "2016") %>% 
  summarise(mean(SuicidePer100000))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
combined_data_set %>% 
  filter(Year == "2016" & Region == "Middle East and Northern Africa" & Sex == "Male") %>% 
  select(Country, HappinessRank)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
combined_data_set %>% 
  filter(Year == "2016" & Region == "Central and Eastern Europe" & Sex == "Male") %>% 
  select(Country, HappinessRank)
```

### Chart C

```{r}
combined_data_set %>% 
  filter(Year == "2016" & Region == "Latin America and Caribbean" & Sex == "Male") %>% 
  select(Country, HappinessRank)
```

### Chart D
```{r}
combined_data_set %>% 
  filter(Year == "2016" & Region == "Southeastern Asia" & Sex == "Male") %>% 
  select(Country, HappinessRank)
```
